---
ATLASSIAN_TENANT: "something.atlassian.net"
USER_EMAIL: "email address for the Atlassian account you're using to create the token (user.name@company.com)"
API_TOKEN: "token ID generated at https://id.atlassian.com/manage/api-tokens"
INCLUDE_ATTACHMENTS: "include attachments? this will make the backup size bigger - true / false"
